FROM python:latest
ENV ᴋʀᴀᴋɪɴᴢʟᴀʙ™ "/venv"
RUN python -m venv $ᴋʀᴀᴋɪɴᴢʟᴀʙ™
ENV PATH "$ᴋʀᴀᴋɪɴᴢʟᴀʙ™/bin:$PATH"
RUN apt update && apt upgrade -y && apt install aptitude -y
RUN aptitude install -y jq git curl wget ffmpeg nodejs npm bpm-tools python3-pip opus-tools python-is-python3 && git clone https://github.com/KryKnz/Vlkyre.git
RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl && chmod a+rx /usr/local/bin/youtube-dl && curl https://cli-assets.heroku.com/install.sh | sh && heroku plugins:install heroku-builds && cd Vlkyre
WORKDIR /Vlkyre
RUN pip install -r 🕊️Adapt/⭕𝖈𝖆𝖗𝖆.txt && npm install -g n pm2 yarn && n install 16 && hash -r && npm install -g spotify-dl spdl-core typescript forever --force && npm install --silent --force
CMD python3 🌱𝖆𝖕𝖗𝖎𝖑𝖑𝖆.py