"◎☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱( Ⓒ𝐁𝐥𝐨𝐨𝐦𝐁𝐨𝐭 (𝐦𝐮𝐥𝐭𝐢-𝐝𝐞𝐯𝐢𝐜𝐞) 𝐛𝐲 𝐌𝐚𝐠𝐧𝐞𝐮𝐦™ )☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱◎";
//  ╔⧉༻ Ⓒ𝐁𝐥𝐨𝐨𝐦𝐁𝐨𝐭 (𝐦𝐮𝐥𝐭𝐢-𝐝𝐞𝐯𝐢𝐜𝐞) 𝐛𝐲 𝐌𝐚𝐠𝐧𝐞𝐮𝐦™
//  ║>>  is a whatsapp user-bot with automation, moderation, music, games and more of 200+ commands!
//  ║
//  ║
//  ║⦁> 🌟 A versatile whatsApp multi-purpose bot designed for group management and user convenience.
//  ║⦁> 🚀 Simplifies group management tasks and enhances the overall user experience.
//  ║⦁> ⚠️ Please note: Engaging in spamming activities may lead to account suspension. Use responsibly!
//  ║⦁> 🎉 BloomBot is intended for fun and convenience, but we're not responsible for account bans.
//  ║⦁> 🔀 forking the repository is allowed, but customized versions or modified plugins are unsupported.
//  ║⦁> ⚠️ Exercise caution and take responsibility for any modifications made to the bot.
//  ║⦁> 📞 Need assistance or have issues? Contact our developers.
//  ║⦁> 🔄 We'll continue providing updates and support for the original version of the bot.
//  ║⦁> 👉 Enjoy the features and functionality of BloomBot responsibly! Make the most out of your
//  ║    whatsApp group management experience! 🎉
//  ║
//  ║     🚨𝐔𝐬𝐚𝐠𝐞 𝐍𝐨𝐭𝐢𝐜𝐞🚨
//  ║⦁>    ⒸBloomBot is in no way affiliated with, authorized, maintained,
//  ║⦁>    sponsored or endorsed by whatsApp or any of its affiliates or
//  ║⦁>    subsidiaries. This is an independent and unofficial software.
//  ║⦁>    Use at your own risk.
//  ║
//  ╚◎ ⚙️Developers: +918436686758, +918250889325
"◎☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱( Ⓒ𝐁𝐥𝐨𝐨𝐦𝐁𝐨𝐭 (𝐦𝐮𝐥𝐭𝐢-𝐝𝐞𝐯𝐢𝐜𝐞) 𝐛𝐲 𝐌𝐚𝐠𝐧𝐞𝐮𝐦™ )☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱☱◎";
const mongoose = require("mongoose");
const dBoardSchema = new mongoose.Schema({
  Id: String,
  profile: String,
  username: String,
  bite: Number,
  blush: Number,
  bonk: Number,
  bored: Number,
  confused: Number,
  cry: Number,
  cuddle: Number,
  dance: Number,
  goodnight: Number,
  happy: Number,
  highfive: Number,
  hug: Number,
  kill: Number,
  kiss: Number,
  nervous: Number,
  pat: Number,
  poke: Number,
  poke: Number,
  punch: Number,
  sad: Number,
  scream: Number,
  slap: Number,
  smile: Number,
  stare: Number,
  wave: Number,
  wink: Number,
  yeet: Number,
  yes: Number,
  sticker: Number,
  tinyurl: Number,
  toimg: Number,
  tourl: Number,
  carbon: Number,
  ship: Number,
  tts: Number,
  ytaudio: Number,
  panning: Number,
  bassbost: Number,
  echo: Number,
  flanger: Number,
  nightcore: Number,
  phaser: Number,
  reverse: Number,
  slow: Number,
  speed: Number,
  subboost: Number,
  superslow: Number,
  superspeed: Number,
  surround: Number,
  vaporwave: Number,
  vibrato: Number,
  balance: Number,
  buy: Number,
  daily: Number,
  fish: Number,
  gamble: Number,
  inv: Number,
  pay: Number,
  rob: Number,
  store: Number,
  work: Number,
  zoo: Number,
  antilink: Number,
  allownsfw: Number,
  delete: Number,
  demote: Number,
  group: Number,
  promote: Number,
  kick: Number,
  setdesc: Number,
  seticon: Number,
  tagall: Number,
  image: Number,
  whats: Number,
  pinterest: Number,
  waifu: Number,
  wallpaper: Number,
  advice: Number,
  anime: Number,
  fact: Number,
  google: Number,
  chordlist: Number,
  getChord: Number,
  pokedex: Number,
  gify: Number,
  lyrics: Number,
  ytsearch: Number,
  instagram: Number,
  joke: Number,
  manga: Number,
  meme: Number,
  quote: Number,
  reddit: Number,
  ytpanning: Number,
  ytbassboost: Number,
  ytecho: Number,
  ytflanger: Number,
  ytnightcore: Number,
  ytphaser: Number,
  ytreverse: Number,
  ytslow: Number,
  ytspeed: Number,
  ytsubboost: Number,
  ytsuperslow: Number,
  ytsuperspeed: Number,
  ytsurround: Number,
  ytvaporwave: Number,
  ytvibrato: Number,
  nsfw: Number,
  nsfw2: Number,
  bonermaterial: Number,
  nsfw411: Number,
  iwanttofuckher: Number,
  exxxtras: Number,
  distension: Number,
  bimbofetish: Number,
  christiangirls: Number,
  dirtygaming: Number,
  sexybutnotporn: Number,
  femalepov: Number,
  omgbeckylookathiscock: Number,
  sexygirls: Number,
  breedingmaterial: Number,
  canthold: Number,
  toocuteforporn: Number,
  justhotwomen: Number,
  stripgirls: Number,
  hotstuffnsfw: Number,
  uncommonposes: Number,
  gifsofremoval: Number,
  nostalgiafapping: Number,
  truefmk: Number,
  nudes: Number,
  p4k: Number,
  realgirls: Number,
  blowjobs: Number,
  milf: Number,
  milk: Number,
  milking: Number,
  lactating: Number,
  pussy: Number,
  cum: Number,
  slut: Number,
  cumslut: Number,
  ban: Number,
  broadcast: Number,
  join: Number,
  leave: Number,
  reboot: Number,
  rules: Number,
  unban: Number,
  verify: Number,
  ass: Number,
  bdsm: Number,
  blowjob: Number,
  cum: Number,
  doujin: Number,
  feet: Number,
  femdom: Number,
  whatsgirl: Number,
  glasses: Number,
  hentai: Number,
  maid: Number,
  masturbation: Number,
  netorare: Number,
  orgy: Number,
  panties: Number,
  pussy: Number,
  school: Number,
  succubus: Number,
  tentacles: Number,
  thighs: Number,
  uglyBastard: Number,
  uniform: Number,
  yuri: Number,
  zettaiRyouiki: Number,

  waifu: Number,
  swaifu: Number,
  whats: Number,
  shinobu: Number,
  megumin: Number,
  awoo: Number,
  sbully: Number,
  scuddle: Number,
  scry: Number,
  shug: Number,
  skiss: Number,
  slick: Number,
  spat: Number,
  ssmug: Number,
  sbonk: Number,
  syeet: Number,
  sblush: Number,
  ssmile: Number,
  swave: Number,
  shighfive: Number,
  shandhold: Number,
  snom: Number,
  sbite: Number,
  sglomp: Number,
  sslap: Number,
  skill: Number,
  skick: Number,
  shappy: Number,
  swink: Number,
  spoke: Number,
  sdance: Number,
  scringe: Number,

  list: Number,
  BloomBot: Number,
  dashboard: Number,
  animationlist: Number,
  audiofilterlist: Number,
  conversionlist: Number,
  downloadlist: Number,
  gameslist: Number,
  grouplist: Number,
  ownerlist: Number,
  photolist: Number,
  searchlist: Number,
  ytfilterlist: Number,
  hentailist: Number,
  nsfwlist: Number,
  sfwlist: Number,
});
module.exports = mongoose.model("dBoard", dBoardSchema);
