name: ci

on: [push, pull_request, workflow_dispatch]

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install FFMPEG
        run: |
          brew install ffmpeg
          brew install pkg-config
          which ffmpeg
          ffmpeg -version

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install --ignore-scripts

      - name: Run tests
        run: |
          npm test
