var mongoose = require("mongoose");
var dBoardSchema = new mongoose.Schema({
  ID: String,
  profile: String,
  username: String,

  bite: Number,
  blush: Number,
  bonk: Number,
  bored: Number,
  confused: Number,
  cry: Number,
  cuddle: Number,
  dance: Number,
  goodnight: Number,
  happy: Number,
  highfive: Number,
  hug: Number,
  kill: Number,
  kiss: Number,
  nervous: Number,
  pat: Number,
  poke: Number,
  poke: Number,
  punch: Number,
  sad: Number,
  scream: Number,
  slap: Number,
  smile: Number,
  stare: Number,
  wave: Number,
  wink: Number,
  yeet: Number,
  yes: Number,

  sticker: Number,
  tinyurl: Number,
  toimg: Number,
  tourl: Number,
  carbon: Number,
  ship: Number,
  tts: Number,

  ytaudio: Number,
  ytvideo: Number,

  panning: Number,
  bassbost: Number,
  echo: Number,
  flanger: Number,
  nightcore: Number,
  phaser: Number,
  reverse: Number,
  slow: Number,
  speed: Number,
  subboost: Number,
  superslow: Number,
  superspeed: Number,
  surround: Number,
  vaporwave: Number,
  vibrato: Number,

  balance: Number,
  buy: Number,
  daily: Number,
  fish: Number,
  gamble: Number,
  inv: Number,
  pay: Number,
  rob: Number,
  store: Number,
  work: Number,
  zoo: Number,

  antilink: Number,
  delete: Number,
  demote: Number,
  group: Number,
  promote: Number,
  kick: Number,
  setdesc: Number,
  seticon: Number,
  tagall: Number,

  image: Number,
  neko: Number,
  pinterest: Number,
  waifu: Number,
  wallpaper: Number,

  advice: Number,
  anime: Number,
  fact: Number,
  google: Number,
  chordlist: Number,
  getChord: Number,
  pokedex: Number,
  gify: Number,
  lyrics: Number,
  ytsearch: Number,
  instagram: Number,
  joke: Number,
  manga: Number,
  meme: Number,
  quote: Number,
  reddit: Number,

  ytpanning: Number,
  ytbassboost: Number,
  ytecho: Number,
  ytflanger: Number,
  ytnightcore: Number,
  ytphaser: Number,
  ytreverse: Number,
  ytslow: Number,
  ytspeed: Number,
  ytsubboost: Number,
  ytsuperslow: Number,
  ytsuperspeed: Number,
  ytsurround: Number,
  ytvaporwave: Number,
  ytvibrato: Number,

  p4k: Number,
  pblowjob: Number,
  pmilf: Number,
  pmilk: Number,
  ppussy: Number,
  pslut: Number,
  tikporn: Number,

  ban: Number,
  broadcast: Number,
  join: Number,
  leave: Number,
  reboot: Number,
  rules: Number,
  unban: Number,
  verify: Number,

  ass: Number,
  bdsm: Number,
  blowjob: Number,
  cum: Number,
  doujin: Number,
  feet: Number,
  femdom: Number,
  foxgirl: Number,
  glasses: Number,
  hentai: Number,
  maid: Number,
  masturbation: Number,
  netorare: Number,
  orgy: Number,
  panties: Number,
  pussy: Number,
  school: Number,
  succubus: Number,
  tentacles: Number,
  thighs: Number,
  uglyBastard: Number,
  uniform: Number,
  yuri: Number,
  zettaiRyouiki: Number,

  menu: Number,
  vlkyre: Number,
  dashboard: Number,

  animationmenu: Number,
  audiofiltermenu: Number,
  conversionmenu: Number,
  downloadmenu: Number,
  gamesmenu: Number,
  groupmenu: Number,
  ownermenu: Number,
  photomenu: Number,
  searchmenu: Number,
  ytfiltermenu: Number,
  hentaimenu: Number,
  adultmenu: Number,
});
module.exports = mongoose.model("dBoard", dBoardSchema);
